# 03. 넘파이
- 정의: NumPy는 Numerical Python을 의미하며, 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 장점: 대량 데이터의 매우 빠른 배열 연산이 가능, 다양한 데이터 핸들링 기능을 제공
- 단점: 편의성과 API 지원 측면에서 2차원 형태의 행렬이라는 점에서 다양한 가공과 변환, 통계용 함수의 적용이 필요

**(1) 넘파이 ndarray 개요**

In [ ]:
import numpy as np

- 정의: 넘파이의 기반 데이터 타입
- 기능: 다차원 배열 생성, 다양한 연산 수행

**array()**
- 정의: 리스트 등 인자를 ndarray로 변환하는 함수

**ndarray**
- .shape: ndarray의 크기를 튜플(tuple) 형태로 나타냄
- .ndim: ndarray의 차원

In [ ]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)  #shape

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))  #ndim

array1: 1차원, array2: 2차원, array3:  2차원


**(2) ndarray의 데이터 타입**
- .dtype: ndarray의 데이터 타입. 한 개의 ndarray에는 같은 데이터 타입만 가능. 데이터 유형이 섞여 있는 경우, 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄 적용
- astype(): 원하는 데이터 타입 지정

In [ ]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)  #dtype

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)  #int형+문자열 -> 문자열로 변환

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)  #int형+float형 -> float64형으로 변환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


**(3) ndarray 편리하게 생성하기**
- arange(): start부터 stop-1 생성 / start의 default값은 0
- zeros(): 모든 값을 0으로 채운 ndarray / shape 지정
- ones(): 모든 값을 1로 채운 ndarray / shape 지정

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)  #arange

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)  #zeros

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)  #ones

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


**(4) ndarray의 차원과 크기 변경**
- reshape(): 원하는 크기를 인자로 부여하여 차원과 크기 변경

In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array:\n', array3)  #reshape

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# array1.reshape(4,3)  ##지정된 사이즈로 변경이 불가능하면 오류 발생

In [ ]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)  #인자에 -1을 넣으면 효율적으로 shape 변환 가능

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
# array1 = np.aragne(10)
# array4 = array1.reshape(-1,4)  ##-1 인자를 사용하더라도 호환 불가능한 형태는 변환 불가

- tolist(): 리스트 자료형으로 변환

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원으로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원으로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)  #tolist()

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


**(5) ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)**

1.   특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됨. [] 안에 특정한 값 입력


In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2] #index는 0부터 시작 -> array1[2]는 3번째 index 위치의 데이터값을 의미
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두번째 값:', array1[-2])  #마이너스 기호(-) 사용 시 뒤에서부터의 순서

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)  #단일 인덱스로 ndarray 수정 가능

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)  #다차원(3*3) ndarray

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


2.   슬라이싱(Slicing): 연속된 인덱스상의 ndarray를 추출하는 방식. ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray 반환

In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)  #:앞의 시작 인덱스 생략 시, 0으로 간주

array5 = array1[3:]
print(array5)  #:뒤의 종료 인덱스 생략 시, 맨 마지막 인덱스로 간주

array6 = array1[:]
print(array6)  #모두 생략 시, 0/맨 마지막 인덱스로 간주

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)  #2차원 ndarray

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[0:2, 0]\n', array2d[:2, 0])  #row(행)/column(열) index 지칭

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[0:2, 0]
 [1 4]


In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


3. 팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0, 1], 2]  #(0,2),(1,2) 인덱싱 적용
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]  #((0,0),(0,1)),((1,0),(1,1)) 인덱싱 적용
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5 = array2d[[0, 1]]  #((0,:),(1,:)) 인덱싱 적용
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


4. 불린 인덱싱(Boolean Indexing)
- 정의: 특정 조건에 해당하는지 여부인 T/F 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환
- 작동 단계: ndarray의 필터링 조건 [] 안에 기재 -> False값은 무시, True에 해당하는 인덱스값만 저장 -> 저장된 인덱스 데이터 세트로 ndarray 조회

In [ ]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d>5 Boolean Indexing 적용
array3 = array1d[array1d > 5]
print('array1d >  5 인덱싱 결과 값:', array3)

array1d >  5 인덱싱 결과 값: [6 7 8 9]


In [ ]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [ ]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


**(6) 행렬의 정렬**
1. 행렬 정렬
- np.sort(): 기존 행렬 유지+정렬된 행렬 반환
- ndarray.sort(): 기존 행렬 자체를 정렬한 형태로 변환, 반환 값은 None

* 기본적으로 오름차순으로 행렬 내 원소 정렬. 내림차순으로 정렬하기 위해서는 [::-1] 적용 필요

In [ ]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)  #원본 행렬 변경 X, 정렬된 형태로 반환

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 후 원본 행렬:', org_array)  #원본 행렬 자체를 정렬한 값으로 변환

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 후 반환된 정렬 행렬: None
org_array.sort() 후 원본 행렬: [1 3 5 9]


In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
array2d = np.array([[8, 12],
                    [7, 1]])  #행렬이 2차원인 경우, row/column 방향 설정 가능
sort_array2d_axis0 = np.sort(array2d, axis = 0)  #axis=0은 열 방향
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)  #axis=1은 행 방향
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


2. 정렬된 행렬의 인덱스 반환
- np.argsort()

In [ ]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)  #[::-1]로 내림차순 정

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


(7) 선형대수 연산
1. 행렬 내적(행렬 곱)
- np.dot()

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


2. 전치 행렬
- transpose()

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
